#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Motor,  port2,           Brush,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Turn,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           right,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           left,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{int pos;
	pos = 0;
	int button;
	button = 0;

	while(true)
	{if(vexRT[Btn8R] == 1)
		{
			button = 1;
		}

		if(vexRT[Btn8D] == 1)
		{
			button = 0;
		}

		if(button == 0)
		{
			motor[port8] = 0;
			motor[port9] = 0;
			motor[port3] = 0;
			motor[port2] = 0;
		}

		if(button == 1)
		{
			motor[port2] = 25;
			motor[port8] = 25;
			motor[port9] = 25;
			motor[port3] = 0;
			if(SensorValue(dgtl1) == 1 && pos == 0)
			{
				motor[port8] = -25;
				motor[port9] = -25;
				wait1Msec(1000);
				motor[port8] = -25;
				motor[port9] = 25;
				motor[port3] = 25;
				wait1Msec(1200);
				motor[port8] = 25;
				motor[port9] = 25;
				motor[port3] = 0;
				wait1Msec(1000);
				motor[port8] = -25;
				motor[port9] = 25;
				motor[port3] = 25;
				wait1Msec(1200);
				motor[port8] = 0;
				motor[port9] = 0;
				motor[port3] = 0;
				pos = 1;
			}
			if(SensorValue(dgtl1) == 1 && pos == 1)
			{
				motor[port8] = -25;
				motor[port9] = -25;
				wait1Msec(1000);
				motor[port8] = 25;
				motor[port9] = -25;
				motor[port3] = -25;
				wait1Msec(1150);
				motor[port8] = 25;
				motor[port9] = 25;
				motor[port3] = 0;
				wait1Msec(1000);
				motor[port8] = 25;
				motor[port9] = -25;
				motor[port3] = -25;
				wait1Msec(1150);
				motor[port3] = 0;
				pos = 0;

			}
		}
	}
}
